apiVersion: v1
kind: Service
metadata:
  labels:
    app: vehicle-license-plate-recognition
  name: vehicle-license-plate-recognition
  namespace: hyperfaas
spec:
  clusterIP: None
  ports:
    - port: 5000
  selector:
    app: vehicle-license-plate-recognition

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vehicle-license-plate-recognition
  namespace: hyperfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vehicle-license-plate-recognition
    spec:
      containers:
      - name: vehicle-license-plate-recognition
        image: cfnorg/carplate:0.1.0
        ports:
        - name: carplate-grpc
          containerPort: 5000
          protocol: TCP
      serviceAccount: hyperfaas-svc
