apiVersion: hyperfaas.io/v1
kind: Function
metadata:
  name: fetch-stock-price
  namespace: admin
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
  environment:
    name: node-env
    namespace: admin
  package:
    packageref:
      name: fetch-stock-price-package
      namespace: admin

---
apiVersion: hyperfaas.io/v1
kind: Package
metadata:
  name: fetch-stock-price-package
  namespace: admin
spec:
  source:
    type: github
    github:
      owner: DevNetSandbox
      repo: sbx_hyperfaas
      path: "stock-price-alerting-service/fetch-stock-price.js"
      ref: master
  environment:
    name: node-env
    namespace: admin
