apiVersion: hyperfaas.io/v1
kind: Function
metadata:
  name: post-to-webex-teams
  namespace: admin
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
  environment:
    name: node-env
    namespace: admin
  package:
    packageref:
      name: post-to-webex-teams-package
      namespace: admin

---
apiVersion: hyperfaas.io/v1
kind: Package
metadata:
  name: post-to-webex-teams-package
  namespace: admin
spec:
  source:
    type: github
    github:
      owner: DevNetSandbox
      repo: sbx_hyperfaas
      path: "stock-price-alerting-service/post-to-webex-teams.js"
      ref: master
environment:
  name: node-env
  namespace: admin
