apiVersion: hyperfaas.io/v1
kind: Function
metadata:
  name: hello-number-nodejs
  namespace: admin
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
  environment:
    name: node-env
    namespace: admin
  package:
    packageref:
      name: hello-number-nodejs-package
      namespace: admin

---
apiVersion: hyperfaas.io/v1
kind: Package
metadata:
  name: hello-number-nodejs-package
  namespace: admin
spec:
  source:
    type: github
    github:
      owner: DevNetSandbox
      repo: sbx_hyperfaas
      path: "basic-workflow/hello-number.js"
      ref: master
environment:
  name: node-env
  namespace: admin
