apiVersion: hyperfaas.io/v1
kind: Function
metadata:
  name: generate-thumbnails
  namespace: admin
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
  environment:
    name: python-env
    namespace: admin
  package:
    functionName: "generate.main"
    packageref:
      name: generate-thumbnails-package
      namespace: admin

---
apiVersion: hyperfaas.io/v1
kind: Package
metadata:
  name: generate-thumbnails-package
  namespace: admin
spec:
  buildcmd: ./build.sh
  source:
    type: github
    build: true
    github:
      owner: DevNetSandbox
      repo: sbx_hyperfaas
      path: "image-processing-vehicle-licence-plate-recognition/functions/generate-thumbnails/"
      ref: master
  environment:
    name: python-env
    namespace: admin
