apiVersion: hyperfaas.io/v1
kind: Environment
metadata:
  name: node-env
  namespace: admin
spec:
  poolsize: 1
  builder:
    image: cfnorg/node-build-env
  runtime:
    image: cfnorg/node-env:graphics
  version: 2
