apiVersion: hyperfaas.io/v1
kind: Function
metadata:
  name: recognize
  namespace: admin
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
  environment:
    name: go-env
    namespace: admin
  package:
    functionName: "Handler"
    packageref:
      name: recognize-package
      namespace: admin

---
apiVersion: hyperfaas.io/v1
kind: Package
metadata:
  name: recognize-package
  namespace: admin
spec:
  buildcmd: build
  source:
    type: github
    build: true
    github:
      owner: DevNetSandbox
      repo: sbx_hyperfaas
      path: "image-processing-vehicle-licence-plate-recognition/functions/recognize"
      ref: "master"
  environment:
    name: go-env
    namespace: admin
