apiVersion: hyperfaas.io/v1alpha1
kind: Workflow
metadata:
  name: vehicle-license-plate-recognition
  namespace: admin
spec:
  environment:
    name: workflow-env
    namespace: admin
  wfDefinition:
    output: PassResult
    tasks:
      PassPicture:
        run: pass-picture
        inputs:
          default: "{$.Invocation.Inputs.default}"
          headers: "{$.Invocation.Inputs.headers}"

      Recognize:
        run: recognize
        inputs: "{$.Tasks.PassPicture.Output}"
        requires:
        - PassPicture

      PassResult:
        run: pass-result
        inputs: "{$.Tasks.Recognize.Output}"
        requires:
        - Recognize
