apiVersion: hyperfaas.io/v1
kind: Function
metadata:
  name: hello
  namespace: admin
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
  environment:
    name: node-env
    namespace: admin
  package:
    packageref:
      name: hello-package
      namespace: admin

---
apiVersion: hyperfaas.io/v1
kind: Package
metadata:
  name: hello-package
  namespace: admin
spec:
  deployment:
    literal: |-
        module.exports = async function(context) {
            let name = context.request.body.name;
            if (name === undefined || name === "") {
                name = "World"
            }
            return {
                status: 200,
                body: "Hello, "+ name +"!\n"
            };
        }
  type: literal
  environment:
    name: node-env
    namespace: admin
